regions:
- global
#- us-east-2
- us-east-1
#- us-west-1
#- us-west-2
#- ap-east-1
#- ap-south-1
#- ap-northeast-2
#- ap-southeast-1
#- ap-southeast-2
#- ap-northeast-1
#- ca-central-1
#- cn-north-1
#- cn-northwest-1
#- eu-central-1
#- eu-west-1
#- eu-west-2
#- eu-west-3
#- eu-north-1
#- sa-east-1
#- us-gov-east-1
#- us-gov-west-1

account-blacklist:
- "999999999999" # Required Placeholder

accounts:
  "813203487890":
    filters:
      EC2DHCPOption:
      - "dopt-9c2622e7"
      CloudWatchAlarm:
      - "BillingAlarm"
#      EC2InternetGatewayAttachment:
#      - "igw-21cd035a -> vpc-665ec51c"
      SNSTopic:
      - "TopicARN: arn:aws:sns:us-east-1:813203487890:NotifyMe"
      SNSSubscription:
      - "Owner: 813203487890 ARN: arn:aws:sns:us-east-1:813203487890:NotifyMe:0f897075-aff8-4360-905c-1d91f4634ce4"
#      EC2VPC:
#      - "vpc-665ec51c"
#      EC2RouteTable:
#      - "rtb-f126c08f"
#      EC2InternetGateway:
#      - "igw-21cd035a"
#      EC2Subnet:
#      - "subnet-d7afb09d"
#      - "subnet-fbb9f69c"
#      - "subnet-4da0a142"
#      - "subnet-7de4ae53"
#      - "subnet-9df1b9c1"
#      - "subnet-50fd6f6e"
      IAMUser:
      - "terraform"
      IAMGroup:
      - "terraform"
      IAMGroupPolicyAttachment:
      - "terraform -> AdministratorAccess"
      IAMUserGroupAttachment:
      - "terraform -> terraform"
      IAMUserAccessKey:
      - "terraform -> AKIA32VVUPSJBLA2EIG3"
